import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import "react-day-picker/style.css";
import './globals.css';
import { Toaster } from '@/components/ui/toaster';
import Footer from '@/components/footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="bg">
      <body className={inter.className}>
        <main className="min-h-screen max-w-7xl mx-auto">
          {children}
          <Toaster />
        </main>
        <Footer />
      </body>
    </html>
  );
}
